spring:
  application:
    name: GameOnTech

  datasource:
    url: jdbc:postgresql://dpg-d66dt46sb7us73e7m4j0-a/gameon_rcce
    username: gameon_rcce_user
    password: D4u1jMRrcqWP72hfPSSy8Ar0BsyER6Og
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8080
